name: Build and Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Build Tools
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Build
        run: npm install -g web-ext

      - run: web-ext --version
      - run: ls
      - run: cat testfolder/text.txt

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: testfolder/*.txt
